[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "pytaco"
author = "Mariatta Wijaya"
author-email = "mariatta.wijaya@gmail.com"
maintainer = "Mariatta Wijaya"
maintainer-email = "mariatta.wijaya@gmail.com"
home-page = "https://github.com/Mariatta/pytaco"
description-file = "README.rst"
classifiers = ["Programming Language :: Python :: 3.6", "Intended Audience :: Developers", "License :: OSI Approved :: Apache Software License"]
requires-python = ">=3.6"


[tool.flit.scripts]
pytaco = "pytaco:main"
